#!/bin/bash

# Temporary directory for Pi-hole backups

backup="/tmp/piholeBackup"

# Check if the backup directory exists; if not, create it
if [ ! -d "$backup" ]
then
        echo "Creating directory for backup files"
        mkdir $backup && echo "Directory created"
else
        echo "The directory '$backup' already exists"
fi

# Keep only the 3 most recent backups and delete older ones

find "$backup" -maxdepth 1 -type f -printf "%T@ %p\n" | sort -nr | tail -n +4 | cut -d ' ' -f2 | xargs -r -d '\n' rm --

# Run Pi-hole backup

cd "$backup" && pihole -a -t 
